id: P007902
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD19078
  title: 'སྙིང་ཐིག་ཡ་བཞི། '
  author: ''
  volumes:
    23025df76fa94a3a8a93435233e9c96d:
      image_group_id: I2PD19082
      title: Volume 1 of
      volume_number: 1
      total_pages: 570
      base_file: v001.txt
    df51c851b9cd486eb03350dbf0ac0f5b:
      image_group_id: I2PD19083
      title: Volume 2 of
      volume_number: 2
      total_pages: 629
      base_file: v002.txt
    0ab4f57312534dcba2912ba331253d84:
      image_group_id: I2PD19084
      title: Volume 3 of
      volume_number: 3
      total_pages: 624
      base_file: v003.txt
    9931a867a57d42d09337ca58192cb31b:
      image_group_id: I2PD19085
      title: Volume 4 of
      volume_number: 4
      total_pages: 544
      base_file: v004.txt
