id: P007902
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19078
  title: 'སྙིང་ཐིག་ཡ་བཞི། '
  author: ''
  volumes:
    21e341d5ef0345ae877290d8c416bb2c:
      image_group_id: I2PD19082
      title: ''
      volume_number: 1
      total_pages: 570
    233369387e48491c83a5819963ce1e4c:
      image_group_id: I2PD19083
      title: ''
      volume_number: 2
      total_pages: 629
    315634bd2f4c44cba0bf14c41ba30f00:
      image_group_id: I2PD19084
      title: ''
      volume_number: 3
      total_pages: 624
    85a325be669a47daa81c49405da6c1de:
      image_group_id: I2PD19085
      title: ''
      volume_number: 4
      total_pages: 544
ebook_metadata:
  title: 'སྙིང་ཐིག་ཡ་བཞི། '
  author: ''
  sku: P007902
  cover: cover.jpg
  layers:
  - pagination
