id: I3873C19F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:45:59+00:00'
last_modified: '2022-06-09T07:16:24.011802+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19078
  title: 'སྙིང་ཐིག་ཡ་བཞི། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E31A:
      image_group_id: I2PD19082
      title: Volume 1 of
      total_pages: 570
      order: 1
      base_file: E31A.txt
    C33F:
      image_group_id: I2PD19083
      title: Volume 2 of
      total_pages: 629
      order: 2
      base_file: C33F.txt
    4DD4:
      image_group_id: I2PD19084
      title: Volume 3 of
      total_pages: 624
      order: 3
      base_file: 4DD4.txt
    1E9D:
      image_group_id: I2PD19085
      title: Volume 4 of
      total_pages: 544
      order: 4
      base_file: 1E9D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
