id: I3873C19F
legacy_id: P007902
ocr_import_info:
  bdrc_scan_id: W2PD19078
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T12:41:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:12:43.165888+00:00'
last_modified: 2022-08-27 19:16:20.236459
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19078
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19078
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྙིང་ཐིག་ཡ་བཞི།
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.9584694494813384
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD19085:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19085
      total_pages: 544
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD19085.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9652224268259321
    legacy_id: v004
  I2PD19082:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19082
      total_pages: 570
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD19082.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9436913658358694
    legacy_id: v001
  I2PD19084:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19084
      total_pages: 624
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD19084.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9592595377775879
    legacy_id: v003
  I2PD19083:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19083
      total_pages: 629
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD19083.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9621278646622909
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
